name: CI
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACK_NAME: "OlivaGithub"
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Pack
        run: |
          if [ ! $PACK_NAME ]; then
              PACK_NAME=${GITHUB_REPOSITORY##*/} 
          fi
          echo "PACK_NAME=$PACK_NAME" >> $GITHUB_ENV
          cd $PACK_NAME
          zip -r ../$PACK_NAME.opk ./
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACK_NAME }}.opk
          path: ./${{ env.PACK_NAME }}.opk
