name: release
on:
  push:
    branches:
      - main
jobs:
  draft_release:
    name: Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: release-drafter/release-drafter@v5
        name: Draft
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
